# -*- coding: utf-8 -*-
from . import (
    test_contract,
    test_options,
    test_classify,
    test_expand,
    test_scope,
    test_relations,
    test_mermaid,
    test_inspector_base,
    test_patient_safety_acceptance,
    test_service,
    test_domain_english,
    test_company,
    test_pg_catalog,
    test_drift,
    test_security,
    test_lifecycle,
    test_exporters,
    test_diagram,
    test_controllers,
)
